// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Xt4_ivl-DSdAblHsdBanMNMOsdLoA2s',
    appId: '1:324534581450:web:868da2f90ffb9f8f069c33',
    messagingSenderId: '324534581450',
    projectId: 'kelompok3-buku-kontoak',
    authDomain: 'kelompok3-buku-kontoak.firebaseapp.com',
    storageBucket: 'kelompok3-buku-kontoak.firebasestorage.app',
    measurementId: 'G-FTT26LZER4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXgpCeNyN9SSn5FKb0_dyfkAmu0mSKhT8',
    appId: '1:324534581450:android:fca67c193e841a0d069c33',
    messagingSenderId: '324534581450',
    projectId: 'kelompok3-buku-kontoak',
    storageBucket: 'kelompok3-buku-kontoak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACVfuD9oZsdEMDZnj9xE5JR93e-5xu-4k',
    appId: '1:324534581450:ios:8caa47fec4df51da069c33',
    messagingSenderId: '324534581450',
    projectId: 'kelompok3-buku-kontoak',
    storageBucket: 'kelompok3-buku-kontoak.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACVfuD9oZsdEMDZnj9xE5JR93e-5xu-4k',
    appId: '1:324534581450:ios:8caa47fec4df51da069c33',
    messagingSenderId: '324534581450',
    projectId: 'kelompok3-buku-kontoak',
    storageBucket: 'kelompok3-buku-kontoak.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Xt4_ivl-DSdAblHsdBanMNMOsdLoA2s',
    appId: '1:324534581450:web:7d87020637f996b9069c33',
    messagingSenderId: '324534581450',
    projectId: 'kelompok3-buku-kontoak',
    authDomain: 'kelompok3-buku-kontoak.firebaseapp.com',
    storageBucket: 'kelompok3-buku-kontoak.firebasestorage.app',
    measurementId: 'G-FPT4Z9Z26P',
  );
}
