// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeHsmrXYm90dM-NBAD964k7Os1icdJ6Nw',
    appId: '1:318953574242:web:a5bebd006a1dcebbbba63b',
    messagingSenderId: '318953574242',
    projectId: 'chatapp-1596b',
    authDomain: 'chatapp-1596b.firebaseapp.com',
    storageBucket: 'chatapp-1596b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLOiRTbt9MPIdzkgbOOXDxkRyOtFGo5A',
    appId: '1:318953574242:android:8a9f1260da42f449bba63b',
    messagingSenderId: '318953574242',
    projectId: 'chatapp-1596b',
    storageBucket: 'chatapp-1596b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjeh7LRcfJ1K0_baYD05Wnygkad1jROw',
    appId: '1:318953574242:ios:2003ccd7696ae2d2bba63b',
    messagingSenderId: '318953574242',
    projectId: 'chatapp-1596b',
    storageBucket: 'chatapp-1596b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzjeh7LRcfJ1K0_baYD05Wnygkad1jROw',
    appId: '1:318953574242:ios:2003ccd7696ae2d2bba63b',
    messagingSenderId: '318953574242',
    projectId: 'chatapp-1596b',
    storageBucket: 'chatapp-1596b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeHsmrXYm90dM-NBAD964k7Os1icdJ6Nw',
    appId: '1:318953574242:web:953ca5cd227bb05dbba63b',
    messagingSenderId: '318953574242',
    projectId: 'chatapp-1596b',
    authDomain: 'chatapp-1596b.firebaseapp.com',
    storageBucket: 'chatapp-1596b.firebasestorage.app',
  );
}
